package com.example.zhoukao0301.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zhoukao0301.db.GoodsEntity;
import com.example.zhoukao0301.db.MessageEntity;

import com.example.zhoukao0301.db.GoodsEntityDao;
import com.example.zhoukao0301.db.MessageEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsEntityDaoConfig;
    private final DaoConfig messageEntityDaoConfig;

    private final GoodsEntityDao goodsEntityDao;
    private final MessageEntityDao messageEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsEntityDaoConfig = daoConfigMap.get(GoodsEntityDao.class).clone();
        goodsEntityDaoConfig.initIdentityScope(type);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        goodsEntityDao = new GoodsEntityDao(goodsEntityDaoConfig, this);
        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);

        registerDao(GoodsEntity.class, goodsEntityDao);
        registerDao(MessageEntity.class, messageEntityDao);
    }
    
    public void clear() {
        goodsEntityDaoConfig.clearIdentityScope();
        messageEntityDaoConfig.clearIdentityScope();
    }

    public GoodsEntityDao getGoodsEntityDao() {
        return goodsEntityDao;
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

}
